### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by TrySound**
With new versions will be much smaller

### CODE REVIEW

**Comment by MoOx** [comment]
directory-encoder change that much ?

**Comment by TrySound** [comment]
@MoOx I removed extra depdendencies and update xml..something (was removed big tests).

**Comment by TrySound** [comment]
@MoOx I think was saved about 1mb.

**Comment by MoOx** [comment]
Next time, be sure to include the reason in the title of the PR ;)

**Comment by TrySound** [comment]
@MoOx Okay.

**Pull request merged**
