### PR TITLE
Switch to an async api

### PR DESCRIPTION
**Pull request by SleepWalker**
refs #43

It was a mistake to say, that everything will fit in `fixUrl` :)

Nevertheless, I have finished with some draft implementation! And successfully tested it on my project. But there are, probably, quite a lot of changes...

I can reduce the amount of code, but I have some questions:
- according to the old logic `valueCallback` will return `oldUrl` in two cases: when the url should not be processed (`isUrlShouldBeIgnored`) and when `UrlProcessor` returned an empty url. Is the second case expected behavior or it is a bug? For now I've leaved this logic as it is and added warning for the case, when `UrlProcessor` returns bad value.
- For the flow with promises, I need to do two `String.replace` calls per url. I think, that this extra call is not expensive, but I can be wrong. So I've wrote separate code for sync and async replacements for now. If it is ok, I can wrap all `UrlProcessor` results in Promises and drop sync logic to reduce the amount of code.

And another one question: should I polyfill Promise for an old Node.js?

### CODE REVIEW

**Comment by niksy** [comment]
What is the status of this PR? Can we maybe help in getting this PR merged (e.g. testing various use cases)?

**Comment by SleepWalker** [comment]
@niksy I am using it for my projects and waiting for any feedback here.
@MoOx can you take a look?

**Comment by RReverser** [comment]
This is great. Is anyone still looking into this PR? Being able to handle asynchronous external deps would be very helpful.

**Comment by niksy** [comment]
@RReverser unfortunately no, and it's a real shame :( In the mean time, I've found that https://github.com/sebastian-software/postcss-smart-asset is fork of this module but has async support so you can try that. I've been using it myself and it works.

**Comment by jonathantneal** [comment]
This branch is now out of sync with master to the point of conflicts. If there isn’t new activity soon, I would say this should unfortunately be closed.

**Comment by niksy** [comment]
It would be real shame if this is missed opportunity. I think postcss-url is one od the most used PostCSS plugins and having async API (by default, but that's another story) is must have today. Can we do something to merge this?

**Comment by MrMeison** [comment]
Don't panic, I repairing this PR :)

**Comment by SleepWalker** [comment]
@MrMeison There was no comment from maintainers for two years. There is no sense to write any code string, till we know, that this PR will be accepted.

**Comment by sergcen** [comment]
PR will be accepted after @MrMeison will fix conflicts

**Comment by MrMeison** [comment]
goto #134

**Comment by sergcen** [comment]
published `9.0.0` with `beta` dist-tag

**Pull request closed without merging**
