### PR TITLE
Make custom mode usage possible

### PR DESCRIPTION
**Pull request by cakeinpanic**
Hello!
I'm trying to use your module with custom `url()` function, but I figured out you don't pass `to`, `from` and some other params to custom function
I fixed it.

### CODE REVIEW

**Comment by MoOx** [comment]
By bringing this change, you are breaking the current api. I would go for addding new parameters at the end, or via a new object at the end.
Also, to please run "npm test" before pushing your changes to be sure you respect coding convention & that existing tests are not broken. 
And maybe you should add a test somewhere to prove that what your bring worth it :) (+ minimal doc in README)

**Comment by cakeinpanic** [comment]
I wanted to use this feature, but i couldn't because of this issue – this is the best worthiness prove)
I fixed tests and also added backward compatibility within my last commit, so now it's not breaking changes anymore and can be merged)

**Comment by MoOx** [comment]
Great job !

**Comment by MoOx** [comment]
Released as 3.3.0

**Pull request merged**
