### PR TITLE
Avoid base64 on SVG files

### PR DESCRIPTION
**Pull request by bfred-it**
#18

### CODE REVIEW

**Comment by bfred-it** [comment]
I fixed the jscs issues and updated commit message

**Comment by bfred-it** [comment]
New npm release coming soon?

**Comment by MoOx** [comment]
[Released in 1.3.0](https://github.com/postcss/postcss-url/releases/tag/1.3.0)

**Comment by bfred-it** [comment]
Sorry for the duplicate request. I didn't remember that I had already asked 😃

**Pull request merged**
