### PR TITLE
Add rule to isUrlShouldBeIgnored function to fix urlencoded hash symbol

### PR DESCRIPTION
**Pull request by xexys**
This svg is valid, but postcss-url break it with rebase option
https://regex101.com/r/zE5yS7/1

Here is a fix

### CODE REVIEW

**Comment by MoOx** [comment]
Can you provide a test in the code base please?

**Comment by xexys** [comment]
I'm sorry. But I can't. I never write test before :)

**Comment by sergcen** [comment]
included in v6 release

**Comment by xexys** [comment]
Great!)

**Pull request closed without merging**
