### PR TITLE
refactory copy method, fix #34

### LINKED ISSUE #34: copy assets to specified directory?
Right now we can specify `assetPath`, which determines the value or `url(value)` in css, and the destination of the copied asset will be calculated based on this info.
That is very convenient if we want to specify a `url(value)` in css.

I am handling cases where the value in `url(value)` does not matter as long as it is right, but the destination of the copied asset does.

Here is an example.

css file `/path/to/src/page/index/index.css`:
```css
.sp-icon {
  background-image: url(i/sp-icon.png);
}
```
the asset file is `/path/to/src/page/index/i/sp-icon.png`

I want to build css to `/path/to/build/page/index/index.css`, and the sprite to `/path/to/build/sp/sp-icon.png`.

So, in  `/path/to/build/page/index/index.css`, it looks like:

```css
.sp-icon {
  background-image: url(../../sp/sp-icon.png);
}
```

Any idea how to achieve this?

### PR DESCRIPTION
**Pull request by tinchoz49**
Sorry, it was an issue in the new tests but fixed now. everthing is working fine. 

About the issue #34 this is what i did...

tested with this idea of folders:
```
dist/
src/
  images/
    i.jpg
  page/
    index/
      images/
        a.jpg
      index.css     # this file has url('images/a.jpg') and url('../../images/i.jpg')
  main.css          # this file has url('images/i.jpg')
```

postcss set with
```
from: 'src/**/*.css' (example using gulp)
to: 'dist/main.css'
```

Using postcss without an ```assetsPath``` and a ```useHash=false```:

the result is going to be basically the same as the ```src``` folder 
```
dist/
  images/
    i.jpg
  page/
    index/
      images/
        a.jpg
      index.css   # this file has url('images/a.jpg') and url('../../images/i.jpg')
  main.css        # this file has url('images/i.jpg')
```

Using postcss with ```assetsPath``` ('assets') and a ```useHash=false```:
```
dist/
  assets/
    images/
      i.jpg
    page/
      index/
        images/
          a.jpg
  page/
    index/
      index.css   # this file has url('../../assets/page/index/images/a.jpg') and url('../../assets/images/i.jpg')
  main.css        # this file has url('assets/images/i.jpg')
```

Using postcss with ```assetsPath``` ('assets') and a ```useHash=true```:
```
dist/
  assets/
    hashunique(a).jpg
    hashunique(i).jpg
  page/
    index/
      index.css   # this file has url('../../assets/hashunique(a).jpg') and url('../../assets/hashunique(i).jpg')
  main.css        # this file has url('assets/hashunique(i).jpg')
```

### CODE REVIEW

**Comment by MoOx** [comment]
This looks good.
Since modifications seems a bit complicated, and according to the fact that I do not use this feature, can some others might do a code review as well ?
poke @zoubin @lexich

**Comment by zoubin** [comment]
OK, I'll do it

**Comment by zoubin** [comment]
@tinchoz49 Thanks for your work. 

I've read the code carefully, and run some examples to see the effect.
I'm afraid the implemented feature is a little different from what I was expecting in #34 . Perhaps I should have given a more detailed explanation about it.

In `/path/to/src/page/index/index.css` we have:

```css
.sp-icon {
  background-image: url(i/sp-icon.png);
}
```

And the sprite lies in `/path/to/src/index/i`.

I was hoping to specify an **absolute** `assetsPath` like:

```javascript
postcss(url({ assetsPath: '/path/to/build/sp' })
  .process(contents, {
    from: '/path/to/src/page/index/index.css',
    to : '/path/to/build/page/index/index.css'
  })
```

And the expected transformed css contents should be:

```css
.sp-icon {
  background-image: url(../../sp/sp-icon.png);
}
```

As I put all my sprites together in the same directory `sp`, so I need to specify the absolute assets path. Perhaps it should be called `assetsDestination`.

I'm afraid the absolute path will be included in the final css in this pr.

However, since we have three ways to implement the `copy` now, perhaps it is worth further discussion to choose one?

@MoOx @lexich Which case do you deal with more often?

**Comment by tinchoz49** [comment]
Hi @zoubin ! first, it's nothing i enjoy work with postcss and the idea behind, soo i want to help :)

I create a repo to show you my idea of how use postcss-url with the copy method, tell me what do you think about it ;)

https://github.com/tinchoz49/test-postcss-copy

**Comment by tinchoz49** [comment]
Hi @zoubin! how are you?, did you see the example? the idea of the ```assetsPath``` is define a **relative** path from you project, i don't understand what is the scenary that you need to work with absolutes path.

**Comment by zoubin** [comment]
@tinchoz49 Sorry for my delay in responding. I have tried the example.

In the example, `gulp --with-assets-path` gave the `dist` directory:
```
dist/
├── assets
│   ├── images
│   │   └── a.jpg
│   └── page
│       ├── images
│       │   └── b.jpg
│       └── index
│           └── images
│               └── c.png
├── main.css
└── page
    └── index
        └── index.css
```

What I want is something like:

```
dist/
├── assets
│   ├── a.jpg
│   ├── b.jpg
│   └── c.png
├── main.css
└── page
    └── index
        └── index.css
```

`main.css`:

```css
body {
    background: url('assets/images/a.jpg');
}
```

`index.css`:

```css
body {
    background: url('../../assets/c.png')
}

div {
    background: url('../../assets/b.jpg')
}

span {
    background: url('../../assets/a.jpg')
}
```

So, I do not mean to specify the `url` by `assetsPath`, but to specify where all pics go, one directory for all pics.

I've got an idea. How about `assetsPath` being a callback as well as a string?

Things get busy right now. I have to go off. I will give an example in a few hours.

**Comment by tinchoz49** [comment]
thanks for your help @zoubin ! i'm going to wait for the example :D

**Comment by MoOx** [comment]
Sorry if I didn't handle this PR, but I am not using this feature and the changes seems a bit complicated, not sure we should handle that...
Can you rebase + add some doc in the README (in order to easily understand the benefit/changes here)?

**Comment by tinchoz49** [comment]
I understand @MoOx, really. Maybe is better if i do a separate plugin with this feature and close this pull request, what do you think? 
I don't know how explain the benefits of the copy method. In the [example](https://github.com/tinchoz49/test-postcss-copy) that i made the last month you can see how it works. 

In my case, i only use the `the copy method with the hash option` like the `file-loader` + `url-loader` of webpack (that was the first idea of the copy method). With this option i can create a build folder with all necesary files (js, css, assets) to compile my `crosswalk mobile apps`.

But for example, i don't like the option of keep the relative paths of the assets in the copy process. I don't see the benefits in that. The copy method without that option would simplify a lot the code and the process.

**Comment by MoOx** [comment]
I have to admit that maybe this module is becoming too big.

**Comment by TrySound** [comment]
@tinchoz49 fs.exists and fs.existsSync was deprecated. Recommend to use this one [path-exists](https://github.com/sindresorhus/path-exists)

**Comment by MoOx** [comment]
The best thing to do is to not use a fs test at all, and directly try to open, but it's kind of tricky sometimes...

**Comment by TrySound** [comment]
Agree

**Comment by tinchoz49** [comment]
@TrySound i'm going to change that. In the begin i used read directly the file with a `try catch` but the v8 can't optimize functions with try catch inside but did not know that module. thanks!

@MoOx i agree with you and i think is not follow the postcss way, the copy method must be a separated module. I'm going to start a new repo for a plugin called `postcss-copy` or if the community  has a better name to share, is welcome :+1:

**Comment by MoOx** [comment]
@tinchoz49 Did you take a look to postcss-assets ?

**Comment by tinchoz49** [comment]
@MoOx yes! it's a nice plugin, but not follow my idea. I want to something really simple like [webpack-file-loader](https://github.com/webpack/file-loader)

**Pull request closed without merging**
