### PR TITLE
removes dirname involvement into relative AssetsPath

### PR DESCRIPTION
**Pull request by thisconnect**
https://githubcom/postcss/postcss-url/issues/46
please review and test, especially in combination with `postcss-import`, assetsPath + useHash: false

### CODE REVIEW

**Comment by MoOx** [comment]
The only solide way to test is by adding automated test.
You can (from your fork), run "npm install && npm test".
Then add some tests to cover this change.

**Comment by thisconnect** [comment]
Of corse I did `npm t` and everything is fine, but I don't know what the code that I removed was supposed to do, so I can not add test for that.

**Comment by MoOx** [comment]
That's true :/
Any watcher wants to review?

**Comment by thisconnect** [comment]
Involving dirname in relativePath got introduced in this commit https://github.com/postcss/postcss-url/commit/da6fbd3a6c54ca36da37a9bb50122162cf117dd6 ping @tinchoz49
and later modified @akrawitz https://github.com/postcss/postcss-url/commit/59683e5c64d1db38fbb2d729a81632e457b55968 maybe they have a usecase where this is necessary or at least would test if their build fails with `"postcss-url": "thisconnect/postcss-url#Fix-assetsPath"`

**Comment by thisconnect** [comment]
After trying a few other plugins my clear favorite is postcss-import with postcss-copy. My project currently imports animate.css, normalize.css and material-design-icons fonts. postcss-copy has a clear understandable source, I have one small issue that I could locate and find out exactly what is going on (https://github.com/geut/postcss-copy/issues/4)

> I prefer to deprecate the plugin directly when all features have been exported elsewhere.
https://github.com/postcss/postcss-url/issues/43#issuecomment-133676539

This would have saved me at least 1 day :) Anything stopping from deprecating postcss-url?

**Comment by MoOx** [comment]
> 1,976 downloads in the last day 

We need a migration guide for all available option before thinking to deprecate. That said, we can gradually remove some feature in favor of some other plugins.

**Comment by thisconnect** [comment]
I see :)

**Comment by thisconnect** [comment]
I moved to postcss-import & postcss-copy, closing this pr as there are no tests

**Pull request closed without merging**
