### PR TITLE
allow for multiple basePaths

### LINKED ISSUE #72: Convert basePath to path, optionally accepting an array
This will bring the behavior in line with `postcss-import` and allows the module to look for URL assets in various locations. Example: `path: [path.resolve(__dirname, 'src'), path.resolve(__dirname, 'node_modules')]`.

Currently only one path can be supplied, which means resources in `node_modules` for example cannot be found.

The option name `path` seems to be more commonly used than `basePath`, it might help to standardize on that.

### PR DESCRIPTION
**Pull request by rybon**
Fixes #72.

### CODE REVIEW

**Comment by sunesimonsen** [comment]
@MoOx would you consider pulling this in?

**Comment by MoOx** [comment]
@sunesimonsen https://github.com/postcss/postcss-url/issues/79#issuecomment-281305033

**Comment by sergcen** [comment]
hi @sunesimonsen, at the moment I'm working on the next major version, I planned to take your changes and release in version 6.0

**Comment by sunesimonsen** [comment]
@MoOx  thanks - sorry to bother you. I'm happy that somebody took over. @sergcen do you need any help?

**Comment by sunesimonsen** [comment]
@sergcen by the way, these are not my changes, I just happy to need it as well.

**Comment by sergcen** [comment]
v6 released

**Comment by sunesimonsen** [comment]
Thanks

**Comment by sunesimonsen** [comment]
I just upgraded, it works great!!

**Pull request closed without merging**
